<a href="https://colab.research.google.com/github/sbenake/pytorch-c1/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Pytorch

In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.5.0+cu121
True


In [10]:
first_tens = torch. tensor ([[12,10,11,9], [13,15,14,0]])
second_tens = torch. tensor([[1,2,3,4], [5,6,7,8]])
add_tens = first_tens + second_tens
sub_tens = first_tens - second_tens
mul_tens = first_tens * second_tens
div_tens = first_tens / second_tens
print (add_tens)
print (sub_tens)
print (mul_tens)
print (div_tens)
print (add_tens.size())

tensor([[13, 12, 14, 13],
        [18, 21, 21,  8]])
tensor([[11,  8,  8,  5],
        [ 8,  9,  7, -8]])
tensor([[12, 20, 33, 36],
        [65, 90, 98,  0]])
tensor([[12.0000,  5.0000,  3.6667,  2.2500],
        [ 2.6000,  2.5000,  2.0000,  0.0000]])
torch.Size([2, 4])
