<a href="https://colab.research.google.com/github/sbenake/pytorch-c1/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Pytorch

In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.5.0+cu121
False


In [ ]:
first_tens = torch. tensor ([[12,10,11,9], [13,15,14,0]])
second_tens = torch. tensor([[1,2,3,4], [5,6,7,8]])
add_tens = first_tens + second_tens
sub_tens = first_tens - second_tens
mul_tens = first_tens * second_tens
div_tens = first_tens / second_tens
print (add_tens)
print (sub_tens)
print (mul_tens)
print (div_tens)
print (add_tens.size())

tensor([[13, 12, 14, 13],
        [18, 21, 21,  8]])
tensor([[11,  8,  8,  5],
        [ 8,  9,  7, -8]])
tensor([[12, 20, 33, 36],
        [65, 90, 98,  0]])
tensor([[12.0000,  5.0000,  3.6667,  2.2500],
        [ 2.6000,  2.5000,  2.0000,  0.0000]])
torch.Size([2, 4])


In [ ]:
if torch.cuda.is_available(): device = torch.device("cuda")
else: device = torch.device("cpu")
print (device)

cuda


In [ ]:
tens_1 = torch.tensor ([[12,10,11,9], [13,15,14,16]],device=device)
tens_2 = torch.tensor([[1,2,3,4], [5,6,7,8]],device=device)
multi_tens = tens_1 * tens_2
print (multi_tens)

tensor([[ 12,  20,  33,  36],
        [ 65,  90,  98, 128]], device='cuda:0')


# Different ways to create Tensors
https://pytorch.org/docs/stable/torch.html

In [ ]:
import numpy as np

# initialize a tensor from a Python list
tensor_from_list=torch.tensor([1,2,3,4,5])
# initialize a tensor from a tuple, tuples are immutable
tensor_from_tuple=torch.tensor((6,7,8,9,10))
print("Tensor from list:",tensor_from_list)
print("Tensor from tuple:",tensor_from_tuple)

# initialize a tensor from a ndarray
tensor_from_ndarray=torch.tensor(np.array([11,12,13,14,15]))
print("Tensor from array:",tensor_from_ndarray)

Tensor from list: tensor([1, 2, 3, 4, 5])
Tensor from tuple: tensor([ 6,  7,  8,  9, 10])
Tensor from array: tensor([11, 12, 13, 14, 15])


Different functions to create tensors



In [ ]:
tensor_emp = torch.empty(3,4)
print("tensor_emp :",tensor_emp)

tensor_zeros = torch.zeros(3,4)
print("tensor_zeros :",tensor_zeros)

tensor_ones= torch.ones(3,4) * 5
print("tensor_ones :",tensor_ones)

tensor_emp : tensor([[ 1.6096e-21,  4.3240e-41, -2.8916e+26,  3.3008e-41],
        [ 4.4842e-44,  0.0000e+00,  1.5695e-43,  0.0000e+00],
        [ 7.4439e-13,  3.3012e-41,  1.0000e+00,  1.0000e+00]])
tensor_zeros : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_ones : tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


In [ ]:
# tensors initialized by size with random values
# returns a tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(4,5)
print("tensor_rand_un :",tensor_rand_un)

# returns a tensor filled with random numbers from a normal distribution
tensor_rand_norm = torch.randn(5,5)
print("tensor_rand_norm :",tensor_rand_norm)

# returns a tensor filled with random integers generated uniformly
tensor_rand_int = torch.randint(5,10,(4,5))
print("tensor_rand_int :",tensor_rand_int)

tensor_rand_int = torch.randint(5,6,(4,5))
print("tensor_5_int :",tensor_rand_int)

# initialize a tensor of ones
tensor_ones = torch.ones_like(tensor_rand_norm)
print(tensor_ones)

tensor_ones = torch.ones_like(tensor_rand_int)
print(tensor_ones)

tensor_rand_un : tensor([[0.0887, 0.8533, 0.7369, 0.5823, 0.7837],
        [0.6593, 0.7192, 0.2959, 0.0418, 0.8420],
        [0.3057, 0.3999, 0.4916, 0.2440, 0.4045],
        [0.7968, 0.0334, 0.1394, 0.9232, 0.1597]])
tensor_rand_norm : tensor([[ 0.5045,  1.6298, -0.8300,  1.6172,  0.8951],
        [-0.4896, -1.6546,  0.2430, -0.4313, -0.0452],
        [-0.0048,  0.2918, -0.0972,  1.6097,  0.2964],
        [ 0.6055,  0.8849,  1.1003, -0.0145,  0.0403],
        [-0.7452, -0.3456,  0.5348,  0.4434, -0.5615]])
tensor_rand_int : tensor([[8, 6, 9, 6, 6],
        [9, 6, 7, 8, 9],
        [8, 8, 7, 8, 5],
        [9, 6, 9, 7, 9]])
tensor_5_int : tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


# Tensor attributes
knowing device location, datatype, dimension, and rank is very important

In [ ]:
first_tensor = torch.tensor([1,2,3,4,5,6])

torch.device indicates the tensor’s device location

In [ ]:
first_tensor.device

device(type='cpu')

torch.dtype indicates the tensor’s data type

In [ ]:
first_tensor.dtype

torch.int64

torch.shape shows the tensor’s dimensions

In [ ]:
first_tensor.shape

torch.Size([6])

torch.ndim identifies the number of a tensor’s dimensions or rank

In [ ]:
first_tensor.ndim

1

In [ ]:
second_tensor = torch.tensor([[1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18]])
second_tensor.dtype

torch.int64

In [ ]:
second_tensor.shape

torch.Size([3, 6])

In [ ]:
second_tensor.ndim

2

# Tensor data types

In [ ]:
#@title Integer data type tensor
int_tensor= torch.tensor([1,2,3,4,5],dtype=torch.int8)
int_tensor.dtype

torch.int8

In [ ]:
#@title Float data type tensor
float_tensor= torch.tensor([6,7,8,9,10], dtype=torch.float32)
float_tensor.dtype

torch.float32

In [ ]:
#@title Short data type tensor
short_tensor= torch.tensor([6,7,8,9,10], dtype=torch.int16)
short_tensor.dtype

torch.int16

In [ ]:
#@title Casting a tensor to a new data type (1st way)
int_tensor= int_tensor.float()
int_tensor.dtype

torch.float32

In [ ]:
#@title Casting a tensor to a new data type (2nd way)
last_tensor = short_tensor.to(dtype=torch.int8)
last_tensor.dtype

torch.int8

# Creating tensors from random samples

In [ ]:
#@title torch.rand() selects random values from a uniform distribution on the interval [0-1]
torch.manual_seed(111) #  this helps control the randomness and make the results deterministic and reproducible.Setting the seed is crucial if you want your model training process to be consistent.
ten1 = torch.rand(3, 3)

# Random tensor initialization
tensor1 = torch.randn(3) #uniform distribution `randn`
tensor2 = torch.randn(3)

print(ten1)
print(tensor1)
print(tensor2)

tensor([[0.7156, 0.9140, 0.2819],
        [0.2581, 0.6311, 0.6001],
        [0.9312, 0.2153, 0.6033]])
tensor([ 0.2657, -0.3120, -0.2888])
tensor([ 0.7697, -0.0359, -0.3874])


In [ ]:
#@title torch.rand() selects random values from a standard normal distribution

torch.rand(4,4) #normal distribution `rand`

tensor([[0.6334, 0.8580, 0.1572, 0.7853],
        [0.1458, 0.4177, 0.3047, 0.0382],
        [0.5805, 0.2089, 0.3964, 0.3527],
        [0.5514, 0.3021, 0.8046, 0.9331]])

In [ ]:
#@title torch.randint() selects random integers generated uniformly between specified low and high values

torch.randint(-1, 10, (3, 3))

tensor([[ 2,  3,  4],
        [ 3,  8,  9],
        [ 8, -1,  3]])

Creating tensors like other tensors

In [ ]:
#@title Create a tensor of shape (2, 5) filled with ones
starting_tensor = torch.zeros(2,5)
starting_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
#@title Create a tensor with the same size filled with random numbers
torch.manual_seed(111)
rand_tensor=torch.rand_like(starting_tensor)
rand_tensor

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])

In [ ]:
#@title Create a tensor with the same shape filled with ones
torch.ones_like(rand_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
#@title Create a tensor with the same shape filled with provided value
torch.full_like(starting_tensor,7)

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])

In [ ]:
#@title Create a tensor of shape (2, 5) filled with zeros
starting_tensor = torch.zeros(2,5)
starting_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
#@title Create a tensor with the same size filled with random numbers
torch.manual_seed(111)
rand_tensor=torch.rand_like(starting_tensor)
rand_tensor

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])

In [ ]:
#@title Create a tensor with the same shape filled with ones
torch.ones_like(rand_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
#@title Create a tensor with the same shape filled with provided value
torch.full_like(starting_tensor,7)

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])

# Tensor operations

In [25]:
#@title Indexing 1-dim tensor example
one_dim_tensor=torch.tensor([1,2,3,4,5,6])
print(one_dim_tensor[2])
print(one_dim_tensor[2].item())

tensor(3)
3


In [3]:
#@title Slicing 1-dim tensor example
# [start:end:step]
one_dim_tensor[1:4]

tensor([2, 3, 4])

In [7]:
#@title Indexing 2-dim tensor example
two_dim_tensor=torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]])
two_dim_tensor[2][5]

tensor(18)

In [10]:
#@title Slicing 2-dim tensor example
print("first three elements of the 1st row: ",two_dim_tensor[0, 0:7])
print("first four elements of the 2nd row: ",two_dim_tensor[1,0:4])

first three elements of the 1st row:  tensor([1, 2, 3, 4, 5, 6])
first four elements of the 2nd row:  tensor([ 7,  8,  9, 10])


In [21]:
#@title Use indexing to extract the data that meets some criteria
two_dim_tensor[(two_dim_tensor % 4) <= 1]

tensor([ 1,  4,  5,  8,  9, 12, 13, 16, 17, 20, 21, 24])

In [48]:
#@title Combining tensors
second_tensor = torch.stack((one_dim_tensor, torch.flip(one_dim_tensor, dims=[0]),one_dim_tensor, torch.flip(one_dim_tensor, dims=[0])))
rev = torch.flip(two_dim_tensor, dims=[1])
torch.stack((rev , second_tensor,two_dim_tensor))

tensor([[[ 6,  5,  4,  3,  2,  1],
         [12, 11, 10,  9,  8,  7],
         [18, 17, 16, 15, 14, 13],
         [24, 23, 22, 21, 20, 19]],

        [[ 1,  2,  3,  4,  5,  6],
         [ 6,  5,  4,  3,  2,  1],
         [ 1,  2,  3,  4,  5,  6],
         [ 6,  5,  4,  3,  2,  1]],

        [[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]]])

In [49]:
#@title Splitting tensors
first_tensor, second_tensor, third_tensor, fourth_tensor=torch.unbind(two_dim_tensor)
print(first_tensor, second_tensor, third_tensor, fourth_tensor)

tensor([1, 2, 3, 4, 5, 6]) tensor([ 7,  8,  9, 10, 11, 12]) tensor([13, 14, 15, 16, 17, 18]) tensor([19, 20, 21, 22, 23, 24])


In [58]:
#@title Splitting 2-dim tensor
torch.unbind(two_dim_tensor,dim=1)

(tensor([ 1,  7, 13, 19]),
 tensor([ 2,  8, 14, 20]),
 tensor([ 3,  9, 15, 21]),
 tensor([ 4, 10, 16, 22]),
 tensor([ 5, 11, 17, 23]),
 tensor([ 6, 12, 18, 24]))