<a href="https://colab.research.google.com/github/sbenake/pytorch-c1/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Pytorch

In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.5.0+cu121
True


In [10]:
first_tens = torch. tensor ([[12,10,11,9], [13,15,14,0]])
second_tens = torch. tensor([[1,2,3,4], [5,6,7,8]])
add_tens = first_tens + second_tens
sub_tens = first_tens - second_tens
mul_tens = first_tens * second_tens
div_tens = first_tens / second_tens
print (add_tens)
print (sub_tens)
print (mul_tens)
print (div_tens)
print (add_tens.size())

tensor([[13, 12, 14, 13],
        [18, 21, 21,  8]])
tensor([[11,  8,  8,  5],
        [ 8,  9,  7, -8]])
tensor([[12, 20, 33, 36],
        [65, 90, 98,  0]])
tensor([[12.0000,  5.0000,  3.6667,  2.2500],
        [ 2.6000,  2.5000,  2.0000,  0.0000]])
torch.Size([2, 4])


In [11]:
if torch.cuda.is_available(): device = torch.device("cuda")
else: device = torch.device("cpu")
print (device)

cuda


In [13]:
tens_1 = torch. tensor ([[12,10,11,9], [13,15,14,16]],device=device)
tens_2 = torch. tensor([[1,2,3,4], [5,6,7,8]],device=device)
multi_tens = tens_1 * tens_2
print (multi_tens)

tensor([[ 12,  20,  33,  36],
        [ 65,  90,  98, 128]], device='cuda:0')


# Different ways to create Tensors
https://pytorch.org/docs/stable/torch.html

In [15]:
import numpy as np

# initialize a tensor from a Python list
tensor_from_list=torch.tensor([1,2,3,4,5])
# initialize a tensor from a tuple, tuples are immutable
tensor_from_tuple=torch.tensor((6,7,8,9,10))
print("Tensor from list:",tensor_from_list)
print("Tensor from tuple:",tensor_from_tuple)

# initialize a tensor from a ndarray
tensor_from_ndarray=torch.tensor(np.array([11,12,13,14,15]))
print("Tensor from array:",tensor_from_ndarray)

Tensor from list: tensor([1, 2, 3, 4, 5])
Tensor from tuple: tensor([ 6,  7,  8,  9, 10])
Tensor from array: tensor([11, 12, 13, 14, 15])


Different functions to create tensors



In [16]:
tensor_emp = torch.empty(3,4)
print("tensor_emp :",tensor_emp)

tensor_zeros = torch.zeros(3,4)
print("tensor_zeros :",tensor_zeros)

tensor_ones= torch.ones(3,4)
print("tensor_ones :",tensor_ones)

tensor_emp : tensor([[1.7321e-01, 4.3904e-41, 8.1487e-05, 3.3331e-41],
        [8.0742e-05, 3.3331e-41, 2.3988e-05, 3.3331e-41],
        [0.0000e+00, 0.0000e+00, 2.4184e-05, 3.3331e-41]])
tensor_zeros : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_ones : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [24]:
# tensors initialized by size with random values
# returns a tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(4,5)
print("tensor_rand_un :",tensor_rand_un)

# returns a tensor filled with random numbers from a normal distribution
tensor_rand_norm = torch.randn(5,5)
print("tensor_rand_norm :",tensor_rand_norm)

# returns a tensor filled with random integers generated uniformly
tensor_rand_int = torch.randint(5,10,(4,5))
print("tensor_rand_int :",tensor_rand_int)

# initialize a tensor of ones
tensor_ones = torch.ones_like(tensor_rand_norm)
print(tensor_ones)

tensor_ones = torch.ones_like(tensor_rand_int)
print(tensor_ones)

tensor_rand_un : tensor([[0.7437, 0.9737, 0.2842, 0.5953, 0.3228],
        [0.1358, 0.1171, 0.1199, 0.2889, 0.5725],
        [0.1188, 0.0935, 0.7954, 0.2197, 0.9450],
        [0.2817, 0.5582, 0.8449, 0.3925, 0.8303]])
tensor_rand_norm : tensor([[-1.8483, -0.0418,  2.5661, -0.7172,  0.2884],
        [ 0.6653, -0.1430,  1.0868, -1.5998, -2.5973],
        [-0.4691, -0.5786,  0.6697,  1.7914,  0.8420],
        [-0.0506,  2.1877, -0.9652, -0.2349,  1.5185],
        [-2.1046, -1.3096,  0.3948, -0.0649, -0.2558]])
tensor_rand_int : tensor([[6, 9, 7, 7, 6],
        [9, 5, 5, 6, 5],
        [7, 8, 5, 7, 5],
        [6, 5, 6, 7, 7]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
